services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - chatcloud-network

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "9901:9901"  # Admin interface
      - "8080:8080"  # gRPC-Web proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - chatcloud-network

  backend:
    build: ./backend
    ports:
      - "50051:50051"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - chatcloud-network
      
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Expose on port 3000 (maps to container's port 80)
    depends_on:
      - envoy
      - backend
    restart: unless-stopped
    networks:
      - chatcloud-network

volumes:
  redis-data:

networks:
  chatcloud-network:
    driver: bridge
